version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - SERVER_URL = http://backend:3001
  backend:
    build:
      context: ./node-postgres/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_CLIENT= http://localhost:3000
      - DB_USER=postgres
      - DB_HOST=10.136.6.177
      - DB_DATABASE=zelis-ideathon
      - DB_PASSWORD=postgres
      - DB_PGPORT= 5432
      - DB_PORT=3001
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      DB_DATABASE: zelis-ideathon
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5432:5432"
