version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - SERVER_URL=http://backend:3001
    networks:
      - appnetwork
  backend:
    build:
      context: ./node-postgres/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_CLIENT=http://localhost:3000
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_DATABASE=zelis-ideathon
      - DB_PASSWORD=postgres
      - DB_PORT=3001
    depends_on:
      - postgres
    networks:
      - appnetwork
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      DB_DATABASE: zelis-ideathon
      DB_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnetwork
    
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
