version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./src/screens/config.dev.json:/app/config.dev.json
    networks:
      - fnet
  backend:
    build:
      context: ./node-postgres/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./node-postgres/backend/.env.dev
    depends_on:
      - postgres
    networks:
      - fnet
  db_postgres:
    image: postgres
    environment:
      - POSTGRES_DB=ideathon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Zelis_12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fnet
    
networks:
  fnet:
    driver: bridge
volumes:
  postgres_data:
